name: r3bin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    cloud_firestore: ^5.6.0
    firebase_auth: ^5.3.4
    firebase_core: ^3.9.0
    flutter:
        sdk: flutter
    google_fonts: ^6.1.0
    intl: ^0.20.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
